server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
#  http2:
#    enabled: true
#
#  ssl:
#    key-store: keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: spring

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb3 # mysql? ??? database? ???????.
    username: rhkdrod12
    password: skgodsla!12
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
#      data-source-properties:
#        rewriteBatchedStatements: true
#        # ???
#        # DB? ??? ??? ?? ?? ???
#        profileSQL: true
#        logger: Slf4JLogger
#        maxQuerySizeToLog: 999999
        
  jpa:
#    show-sql: true  # DB? ??? SQL?? ???? ??
    hibernate:
      ddl-auto: none # DDL?? ??????? ???? ??
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true  # ?????? SQL? ???? ?? ??
#        jdbc.batch_size: 500
#        order_inserts: true  # batch_size? ?? insert? ?? ? insert? ??? ?? ??
#        order_updates: true  # ?? ?? ?? update?
    open-in-view: false